# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# MRARFAI V10.1 — A2A gRPC 消息定义 (手动 stub)
#
# 正式编译命令:
#   pip install grpcio-tools
#   python -m grpc_tools.protoc -I proto \
#     --python_out=. --grpc_python_out=. \
#     proto/a2a_service.proto
#
# 本文件为手动 stub，提供与 protobuf 兼容的消息接口。
# 安装 grpcio-tools 后可重新编译覆盖。

"""A2A gRPC Message Stubs — 兼容 protobuf 接口"""


class A2ARequest:
    """JSON-RPC 风格通用请求"""
    DESCRIPTOR = None

    def __init__(self, json_payload: str = ""):
        self.json_payload = json_payload

    def SerializeToString(self) -> bytes:
        return self.json_payload.encode("utf-8")

    @classmethod
    def FromString(cls, data: bytes):
        obj = cls()
        obj.json_payload = data.decode("utf-8")
        return obj


class A2AResponse:
    """JSON-RPC 风格通用响应"""
    DESCRIPTOR = None

    def __init__(self, json_payload: str = ""):
        self.json_payload = json_payload

    def SerializeToString(self) -> bytes:
        return self.json_payload.encode("utf-8")

    @classmethod
    def FromString(cls, data: bytes):
        obj = cls()
        obj.json_payload = data.decode("utf-8")
        return obj


class AgentCardRequest:
    """Agent Card 请求 (空消息)"""
    DESCRIPTOR = None

    def SerializeToString(self) -> bytes:
        return b""

    @classmethod
    def FromString(cls, data: bytes):
        return cls()


class AgentCardResponse:
    """Agent Card 响应"""
    DESCRIPTOR = None

    def __init__(self, card_json: str = ""):
        self.card_json = card_json

    def SerializeToString(self) -> bytes:
        return self.card_json.encode("utf-8")

    @classmethod
    def FromString(cls, data: bytes):
        obj = cls()
        obj.card_json = data.decode("utf-8")
        return obj


class StreamEvent:
    """流式事件"""
    DESCRIPTOR = None

    def __init__(self, event_json: str = ""):
        self.event_json = event_json

    def SerializeToString(self) -> bytes:
        return self.event_json.encode("utf-8")

    @classmethod
    def FromString(cls, data: bytes):
        obj = cls()
        obj.event_json = data.decode("utf-8")
        return obj
