# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# MRARFAI V10.1 — A2A gRPC Servicer 定义 (手动 stub)
#
# 正式编译命令:
#   pip install grpcio-tools
#   python -m grpc_tools.protoc -I proto \
#     --python_out=. --grpc_python_out=. \
#     proto/a2a_service.proto

"""A2A gRPC Servicer Stubs — 兼容 grpcio 接口"""

import grpc

from a2a_service_pb2 import (
    A2ARequest, A2AResponse,
    AgentCardRequest, AgentCardResponse,
    StreamEvent,
)


class A2AServiceServicer:
    """A2A gRPC Service — 基类 (子类需实现所有方法)"""

    def GetAgentCard(self, request, context):
        """获取 Agent Card"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendTask(self, request, context):
        """发送任务 (tasks/send)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTask(self, request, context):
        """获取任务状态 (tasks/get)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelTask(self, request, context):
        """取消任务 (tasks/cancel)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamTask(self, request, context):
        """流式任务 (tasks/sendSubscribe)"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


# ============================================================
# 方法描述符 (gRPC 注册所需)
# ============================================================

_SERVICE_NAME = "mrarfai.a2a.A2AService"

# 通用序列化/反序列化 handler
def _serialize(msg):
    return msg.SerializeToString()

def _deserialize_request(data):
    return A2ARequest.FromString(data)

def _deserialize_card_request(data):
    return AgentCardRequest.FromString(data)

def _serialize_response(msg):
    return msg.SerializeToString() if hasattr(msg, 'SerializeToString') else msg

def _deserialize_response(data):
    return A2AResponse.FromString(data)


# 方法处理器定义
_METHODS = {
    "GetAgentCard": grpc.unary_unary_rpc_method_handler(
        None,
        request_deserializer=_deserialize_card_request,
        response_serializer=_serialize,
    ),
    "SendTask": grpc.unary_unary_rpc_method_handler(
        None,
        request_deserializer=_deserialize_request,
        response_serializer=_serialize,
    ),
    "GetTask": grpc.unary_unary_rpc_method_handler(
        None,
        request_deserializer=_deserialize_request,
        response_serializer=_serialize,
    ),
    "CancelTask": grpc.unary_unary_rpc_method_handler(
        None,
        request_deserializer=_deserialize_request,
        response_serializer=_serialize,
    ),
    "StreamTask": grpc.unary_stream_rpc_method_handler(
        None,
        request_deserializer=_deserialize_request,
        response_serializer=_serialize,
    ),
}


def add_A2AServiceServicer_to_server(servicer, server):
    """注册 A2AServiceServicer 到 gRPC Server"""
    from grpc import method_service_handler

    rpc_method_handlers = {
        "GetAgentCard": grpc.unary_unary_rpc_method_handler(
            servicer.GetAgentCard,
            request_deserializer=_deserialize_card_request,
            response_serializer=_serialize,
        ),
        "SendTask": grpc.unary_unary_rpc_method_handler(
            servicer.SendTask,
            request_deserializer=_deserialize_request,
            response_serializer=_serialize,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=_deserialize_request,
            response_serializer=_serialize,
        ),
        "CancelTask": grpc.unary_unary_rpc_method_handler(
            servicer.CancelTask,
            request_deserializer=_deserialize_request,
            response_serializer=_serialize,
        ),
        "StreamTask": grpc.unary_stream_rpc_method_handler(
            servicer.StreamTask,
            request_deserializer=_deserialize_request,
            response_serializer=_serialize,
        ),
    }
    generic_handler = grpc.method_service_handler(
        _SERVICE_NAME, rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))
